openapi: 3.0.1
info:
  title: OpenAPI Specification
  version: 0.0.1-SNAPSHOT
servers:
- url: /api
paths:
  /ping:
    get:
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
